name: wure_baat

description: A language-agnostic word puzzle game inspired by Spelling Bee.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.5.4
  intl: ^0.17.0
  haptic_feedback: ^0.6.4+3
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icon1.png"
  adaptive_icon_background: "#FFFFFF" # Using white as a safe default
  adaptive_icon_foreground: "assets/Icon1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/alphabets/
    - assets/wordlists/
